# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20190418-MohammadAlsharif-NYCSchools' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 20190418-MohammadAlsharif-NYCSchools
  pod 'ReachabilitySwift', '~> 4.0'
  pod 'Alamofire', '~> 4.8.1'
  pod 'MBProgressHUD', '~> 1.1.0'

  target '20190418-MohammadAlsharif-NYCSchoolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '20190418-MohammadAlsharif-NYCSchoolsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
